service: api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-2

plugins:
  - serverless-offline

functions:
  lambda:
    handler: './src/index.handler'
    events:
      - http:
          method: GET
          path: /
          cors: true
