# docker-compose.yml
version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: app-dynamodb
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -inMemory -sharedDb'

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    container_name: app-dynamodb_admin
    ports:
      - '8001:8001'
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
