AWSTemplateFormatVersion: 2010-09-09
Description: 'API Gateway, lambda, iotrule and dynamodb table'

Parameters:
  ProjectPrefix:
    Type: String
    Default: 'demo'
    Description: 'Name of Project prefix'
  ProjectName:
    Type: String
    Default: 'iot-backend'
    Description: 'Name of Project'
  SubDomainName:
    Type: 'String'
    Default: 'api.iot'
    Description: 'Subdomain path'

Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${ProjectPrefix}-dbtable-${ProjectName}'
      AttributeDefinitions:
        - AttributeName: 'time'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'time'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      DeletionProtectionEnabled: true

  IotTopicRule:
    Type: 'AWS::IoT::TopicRule'
    Properties:
      RuleName: tempSensor
      TopicRulePayload:
        Description: !Sub '${ProjectPrefix}-topicrule-${ProjectName}'
        RuleDisabled: false
        Sql: SELECT temp FROM 'tempSensor'
        Actions:
          - DynamoDB:
              HashKeyField: 'time'
              HashKeyType: STRING
              HashKeyValue: '${timestamp()}.'
              PayloadField: 'payload'
              TableName: !Sub '${ProjectPrefix}-dbtable-${ProjectName}'
              RoleArn: !GetAtt IoTRole.Arn
    DependsOn:
      - IoTRole

  IoTRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ProjectPrefix}-role-${ProjectName}-iot'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'iot.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProjectPrefix}-policy-${ProjectName}-db'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'dynamodb:PutItem'
                Resource: !GetAtt DynamoDBTable.Arn
    DependsOn:
      - DynamoDBTable

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectPrefix}-lambda-${ProjectName}'
      RetentionInDays: 14

  Lambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: !Sub '${ProjectPrefix}-lambda-${ProjectName}'
      FunctionName: !Sub '${ProjectPrefix}-lambda-${ProjectName}'
      Code:
        ZipFile: |
          exports.handler = function(event, context, callback) {
            const response = {
              statusCode: 200,
              body: JSON.stringify({ 'msg': 'dummy api response' })
            };
            callback(null, response);
          };
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
    DependsOn:
      - LambdaRole

  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ProjectPrefix}-role-${ProjectName}-lambda'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProjectPrefix}-policy-${ProjectName}-lambda'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'dynamodb:Scan'
                Resource: '*' #!GetAtt DynamoDBTable.Arn
              - Effect: 'Allow'
                Action: logs:*
                Resource: !GetAtt LambdaLogGroup.Arn
    DependsOn:
      - LambdaLogGroup
      - DynamoDBTable

  Api:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Sub '${ProjectPrefix}-api-${ProjectName}'
      ProtocolType: 'HTTP'
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET

  ApiCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub '${SubDomainName}.tomnuttall.dev'
      DomainValidationOptions:
        - DomainName: !Sub '${SubDomainName}.tomnuttall.dev'
          HostedZoneId: 'Z101113538JEKZU2FHGNL'
      ValidationMethod: DNS

  ApiDomain:
    Type: 'AWS::ApiGatewayV2::DomainName'
    Properties:
      DomainName: !Sub '${SubDomainName}.tomnuttall.dev'
      DomainNameConfigurations:
        - EndpointType: 'REGIONAL'
          CertificateArn: !Ref ApiCertificate
    DependsOn:
      - ApiCertificate

  ApiMapping:
    Type: 'AWS::ApiGatewayV2::ApiMapping'
    Properties:
      ApiId: !Ref Api
      DomainName: !Sub '${SubDomainName}.tomnuttall.dev'
      Stage: !Ref ApiStage
    DependsOn:
      - Api
      - ApiDomain
      - ApiStage

  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: 'tomnuttall.dev.'
      Name: !Sub '${SubDomainName}.tomnuttall.dev'
      Type: 'A'
      AliasTarget:
        DNSName: !GetAtt ApiDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiDomain.RegionalHostedZoneId
    DependsOn:
      - Api

  ApiIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref Api
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !GetAtt Lambda.Arn
          - /invocations
      IntegrationMethod: POST
      PayloadFormatVersion: '2.0'
    DependsOn:
      - Lambda
      - Api

  ApiRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /'
      Target: !Sub 'integrations/${ApiIntegration}'
    DependsOn:
      - Api
      - ApiIntegration

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*/'
    DependsOn:
      - ApiRoute

  ApiStage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref Api
      AutoDeploy: true
      StageName: 'dev'
    DependsOn:
      - Api
